extends Node
## The level's sound. Everything is generated by Sfx (no audio files).
##   always:        the building's low hum + a slow, broken music box tune
##   while hunted:  the music box stops, chase music + your heartbeat take over
##   you:           footsteps that match your walking, a thump when you land
##   events:        a chime when you find a toy, a scream when something SEES you,
##                  a screech when something GETS you

@export_group("Volumes (dB)")
@export var hum_db := -18.0
@export var music_db := -13.0
@export var panic_db := -6.0
@export var heartbeat_db := -4.0
@export var footstep_db := -9.0
@export var effects_db := 0.0

## Broken music box tune in E minor. 0 = rest. Played an octave up, slightly out of time.
const MELODY: Array[float] = [
	659.25, 493.88, 392.0, 493.88, 659.25, 493.88, 392.0, 523.25,
	493.88, 392.0, 329.63, 392.0, 622.25, 493.88, 369.99, 0.0,
	659.25, 493.88, 392.0, 493.88, 739.99, 587.33, 493.88, 587.33,
	659.25, 523.25, 440.0, 523.25, 622.25, 493.88, 329.63, 0.0,
]
const NOTE_BASE := 1318.5   # the pitch Sfx's "note" is recorded at
const STRIDE := 1.7         # metres between footsteps

var _hum: AudioStreamPlayer
var _panic: AudioStreamPlayer
var _music: AudioStreamPlayer
var _steps: AudioStreamPlayer
var _fx: AudioStreamPlayer

var _hunted := 0.0          # 0..1 eases in when a monster hunts you
var _beat_timer := 0.0
var _note_index := 0
var _note_timer := 1.5
var _step_dist := 0.0
var _step_variant := 0
var _was_on_floor := true
var _prev_vy := 0.0


func _ready() -> void:
	_hum = _loop_player("hum", hum_db)
	_panic = _loop_player("panic", -60.0)
	_music = _poly_player(music_db)
	_steps = _poly_player(footstep_db)
	_fx = _poly_player(effects_db)
	Game.collected_one.connect(func(): _play(_fx, "chime"))
	Game.spotted.connect(func(_by: Node3D): _play(_fx, "scream"))
	Game.caught.connect(func(_by: Node3D): _play(_fx, "screech"))


func _process(delta: float) -> void:
	var hunted := false
	for m in get_tree().get_nodes_in_group("monster"):
		if m.chasing:
			hunted = true
			break
	_hunted = move_toward(_hunted, 1.0 if hunted else 0.0, delta * (3.0 if hunted else 0.4))
	_panic.volume_db = lerpf(-60.0, panic_db, sqrt(_hunted))
	_music.volume_db = lerpf(music_db, -60.0, _hunted)

	# heartbeat: faster the more scared you are
	if _hunted > 0.01:
		_beat_timer -= delta
		if _beat_timer <= 0.0:
			_beat_timer = 1.0 / lerpf(1.0, 2.8, _hunted)
			_play(_fx, "heart", heartbeat_db + lerpf(-10.0, 0.0, _hunted))

	# music box: one note at a time, never quite in time
	_note_timer -= delta
	if _note_timer <= 0.0 and _hunted < 0.5:
		var f := MELODY[_note_index % MELODY.size()]
		_note_index += 1
		_note_timer = 0.42 * randf_range(0.95, 1.15) + (0.4 if f == 0.0 else 0.0)
		if f > 0.0 and randf() > 0.06:   # sometimes a tine is missing
			_play(_music, "note", randf_range(-3.0, 0.0), f * 2.0 / NOTE_BASE * randf_range(0.995, 1.005))

	_footsteps(delta)


func _footsteps(delta: float) -> void:
	var players := get_tree().get_nodes_in_group("player")
	if players.is_empty() or get_tree().paused:   # the music keeps going on the menus; feet don't
		return
	var p: CharacterBody3D = players[0]
	var on_floor := p.is_on_floor()
	if on_floor and not _was_on_floor and _prev_vy < -4.0:
		_play(_steps, "land", 0.0, randf_range(0.9, 1.1))
		_step_dist = STRIDE * 0.5
	_was_on_floor = on_floor
	_prev_vy = p.velocity.y

	var walking: bool = p.active if "active" in p else true
	var speed := Vector2(p.velocity.x, p.velocity.z).length()
	if walking and on_floor and speed > 1.0:
		_step_dist += speed * delta
		if _step_dist >= STRIDE:
			_step_dist = 0.0
			_step_variant = (_step_variant + 1 + randi() % 3) % 4
			_play(_steps, "step%d" % _step_variant, randf_range(-3.0, 0.0), randf_range(0.9, 1.12))
	else:
		_step_dist = STRIDE * 0.7   # first step comes quickly when you start walking


func _play(player: AudioStreamPlayer, sound: String, db := 0.0, pitch := 1.0) -> void:
	var pb := player.get_stream_playback() as AudioStreamPlaybackPolyphonic
	if pb == null:
		return
	pb.play_stream(Sfx.get_sound(sound), 0.0, db, pitch)


func _loop_player(sound: String, db: float) -> AudioStreamPlayer:
	var player := AudioStreamPlayer.new()
	player.stream = Sfx.get_sound(sound)
	player.volume_db = db
	player.autoplay = true
	add_child(player)
	return player


func _poly_player(db: float) -> AudioStreamPlayer:
	var player := AudioStreamPlayer.new()
	var poly := AudioStreamPolyphonic.new()
	poly.polyphony = 8
	player.stream = poly
	player.volume_db = db
	player.autoplay = true
	add_child(player)
	return player
